'use client';

import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import { useSettingsContext } from 'src/components/settings';
import { Grid, Pagination } from '@mui/material';
import CustomStoryCard from 'src/components/story-cards/customStroyCard';
import { useState, memo } from 'react';
import { getPublicStories } from 'src/apis/create-story';
import { useQuery } from 'react-query';

// ----------------------------------------------------------------------

export default function Discover() {
  const settings = useSettingsContext();
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 8;

  let accessToken;
  if (typeof window !== 'undefined') {
    accessToken = localStorage.getItem('accessToken');
  }
  const { data: publicStoriesData } = useQuery(['getPublicStories', accessToken], () =>
    getPublicStories(accessToken)
  );

  const filteredData = publicStoriesData?.sort(
    (a, b) => new Date(b.createdAt) - new Date(a.createdAt)
  );

  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = filteredData?.slice(indexOfFirstItem, indexOfLastItem);

  const handlePageChange = (event, value) => {
    setCurrentPage(value);
  };

  const MemoizedStoryCard = memo(CustomStoryCard);

  return (
  <Container maxWidth={false} sx={{ maxWidth:'1350px' }}>
      <Box
        sx={{
          mt: 5,
          display: 'flex',
          justifyContent: 'center',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 2,
        }}
      >
        <Typography variant="h2"> Library </Typography>
        <Typography
          variant="body"
          color="textSecondary"
          sx={{ textAlign: 'center', mb: 2, fontSize: { xs: '.9rem', sm: '1rem', md: '1.8rem' } }}
        >
          All books are generated by AI and personalised by you.
        </Typography>
      </Box>
      <Box sx={{ p: { xs: 0, md: 8 } }}>
        {filteredData?.length < 1 ? (
          <Typography variant="h2" textAlign={'center'}>
            {' '}
            No Stories Found{' '}
          </Typography>
        ) : (
          <Grid container spacing={1.5}>
            {currentItems?.map((story) => (
              <Grid item md={3} key={story.id}>
                <MemoizedStoryCard story={story} cursor="pointer" isPublic={true} />
              </Grid>
            ))}
          </Grid>
        )}
        {filteredData?.length > 0 && (
          <Box sx={{ display: 'flex', justifyContent: 'center', mt: 4 }}>
            <Pagination
              variant="outlined"
              color="primary"
              count={Math.ceil(filteredData?.length / itemsPerPage)}
              page={currentPage}
              onChange={handlePageChange}
              size="large"
            />
          </Box>
        )}
      </Box>
    </Container>
  );
}
